added some helper utilities

diff --git a/aurbuild b/aurbuild
--- a/aurbuild
+++ b/aurbuild
@@ -2,23 +2,24 @@
 
 die() {
 	echo $*
-	echo 1
+	exit 1
 }
 
-if ["$1" == "" ]; then
+if [ "$1" == "" ]; then
 	echo "usage: aurbuild <package_name>"
 	echo
 	exit 1
 fi
 pkgname=$1
-[ -d $pkgname ] && die "Directory '$pkgname' already exists"
-[ -f $pkgname ] && die "File '$pkgname' already exists"
+[ -d $pkgname  ] && die "Directory '$pkgname' already exists"
+[ -f $pkgname  ] && die "File '$pkgname' already exists"
 
 pfx=`echo $pkgname | cut -c1-2`
 echo "Downloading $pkgname.tar.gz"
-wget -q http://aur.archlinux.org/package/$pfx/$pkgname/$pkgname.tar.gz || die "Failed to fetch $pkgname.tar.gz"
+wget -q http://aur.archlinux.org/packages/$pfx/$pkgname/$pkgname.tar.gz || die "Failed to fetch $pkgname.tar.gz"
 
 tar zxf $pkgname.tar.gz || die "Extraction failed"
 rm -f $pkgname.tar.gz
 cd $pkgname || die "Failed to cwd"
 makepkg
+
